name    'wcooley-cimlog_report'
version '0.1.0'
author  'wcooley'
license 'Apache License, Version 2.0'
summary 'Report processor to log in Splunk CIM style'
description 'Puppet report processor that logs via syslog and formats data using key=value (or field=value) pairs, as recommended in Splunk\'s CIM documentation.'
project_page 'https://github.com/wcooley/puppet-name_service'
